name: Run unit tests

on:
    workflow_dispatch: # Allow manual trigger
    push:
        branches:
            - main
        paths:
            - "src/**"
            - ".github/workflows/uv-pytest.yml"
    pull_request:
        branches:
            - main
        paths:
            - "sec/**"
            - ".github/workflows/uv-pytest.yml"

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    pytest:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Install the latest version of uv
              uses: astral-sh/setup-uv@v3
              with:
                  version: "latest"

            - name: Run tests
              working-directory: ./app
              run: |
                  uv run pytest
